### ISSUE TITLE
React PropTypes and React.createClass deprecation warnings

### ISSUE THREAD

**Issue by dandonahoe** [react-component/collapse#74]
When including `rc-collapse` in a React `15.5.*` project, two warnings always appear. When React 16 is released, this package will be broken.

- `Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`
- `Warning: AnimateChild: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`

The fix for the proptype warning is pretty simple, just adding a dependency to the replacement package `prop-types` and adding `import PropTypes from 'prop-types';` to any source file with a PropType reference.

**Comment by afc163** [comment]
Fixed in #58, try reinstall latest version.

**Comment by qborreda** [comment]
Sorry for opening back this one, but similarly enough, we can use `className` as a prop passed to Panel, and ESLint warns this is not very desirable ..

**Comment by tomitrescak** [comment]
Installed version 1.7.6 and still getting the warning :/ Which version was this published with ?

**Comment by shepherdwind** [comment]
`AnimateChild` code at https://github.com/react-component/animate/blob/master/src/AnimateChild.js#L13 , React.createClass had removed.

**Comment by tomitrescak** [comment]
Yeah, I went over sources so it's great that it's fixed. But would be really greatfull if you could release this in a new version. Thanks!

**Comment by tomitrescak** [comment]
Please, please, can you do the release with fixed warning? Thanks.

**Comment by shepherdwind** [comment]
@tomitrescak I don't know you want to release which package? rc-collapse or rc-animate ? Those two package should already update to React.Component now.
